version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: brasileirao-db
    ports: 
      - 1433:1433
    user: root
    environment: 
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: "Sasuke3634"
    volumes: 
      - ../volumes/data:/var/opt/mssql/data